// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWKSzrY4mCuCv0DhhNAaI6chOJC3KsB0',
    appId: '1:165422532685:web:7198d89aca2cca4468f404',
    messagingSenderId: '165422532685',
    projectId: 'fl-chat-03',
    authDomain: 'fl-chat-03.firebaseapp.com',
    storageBucket: 'fl-chat-03.appspot.com',
    measurementId: 'G-P1MTG81XKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjtiuznLK8VqrVGLggqyluJEsLw22sqRE',
    appId: '1:165422532685:android:03a5b754f6d5d71868f404',
    messagingSenderId: '165422532685',
    projectId: 'fl-chat-03',
    storageBucket: 'fl-chat-03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-okDrLh0hD1vEeVC7WCgX7vZGNHDEisk',
    appId: '1:165422532685:ios:35f59cde50caa01768f404',
    messagingSenderId: '165422532685',
    projectId: 'fl-chat-03',
    storageBucket: 'fl-chat-03.appspot.com',
    iosClientId: '165422532685-npjajb8kbp21a1agv5fsqt0to50f27ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.flApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-okDrLh0hD1vEeVC7WCgX7vZGNHDEisk',
    appId: '1:165422532685:ios:35f59cde50caa01768f404',
    messagingSenderId: '165422532685',
    projectId: 'fl-chat-03',
    storageBucket: 'fl-chat-03.appspot.com',
    iosClientId: '165422532685-npjajb8kbp21a1agv5fsqt0to50f27ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.flApp3',
  );
}
